### ISSUE TITLE
Mention the new Open Source project sell-your-saas

### ISSUE THREAD

**Issue by eldy** [nicolas-racchi/SaaS4Devs#11]
I think you should mention the open source project https://github.com/eldy/sellyoursaas in your resources.
It is the first (and only project) that offer a full working solution to your saas application (from marketing, deployement of customer instances  to accountancy). 100% of the need is covered so you can start a saas business in only 2 or 3 days.
Just take a look: https://www.sellyoursaas.org

**Comment by nicolas-racchi** [comment]
Hey, thanks for submitting. It seems like a huge project, please help me to understand it a bit more.
Is it correct that this is a platform where to put your existing SaaS product to manage the deployment and other DevOps things, rather than a tool for actually _building_ a company from scratch? 
Sorry if I misunderstood, I found the website not very clear since I'm not an expert in DevOps.

**Comment by eldy** [comment]
It is both:
"a platform where to put your existing SaaS product to manage the deployment and other DevOps things"
and also a tool to
"building a company from scratch"

**Comment by nicolas-racchi** [comment]
Wow, it's very impressive. I'll add it now 😁
